# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
    config.vm.box =  "debian/bullseye64"
    config.vm.hostname = "docker"
    config.vm.provision "shell", path: "install_docker.sh"
    config.vm.provision "shell", path: "scripts/root.sh"
end

